name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@master
        with:
          cache: 'npm'
          # Node 19 introduced a bug in tests, don't use it for now
          # https://github.com/facebook/react-native/issues/36440
          # TODO: Allow newest version if the bug is fixed
          node-version: '18.15.0'

      - name: Install node modules
        run: |
          npm install
      
      - name: Run CI with Lefthook
        run: |
          npx lefthook run ci-hook

      - name: Run test
        run: |
          npm test
