name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@master
        with:
          cache: 'npm'
          node-version: '18.15.0'

      - name: Install node modules
        run: |
          npm install
      
      - name: Run CI with Lefthook
        run: |
          npx lefthook run ci-hook

      - name: Run test
        run: |
          npm test
